/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'documentType' : IDL.Text,
  'blobId' : ExternalBlob,
});
export const LicenseType = IDL.Variant({
  'supervisor' : IDL.Null,
  'wireman' : IDL.Null,
  'workman' : IDL.Null,
});
export const LicenseApplication = IDL.Record({
  'id' : IDL.Nat,
  'nicNumber' : IDL.Text,
  'status' : Status,
  'applicant' : IDL.Principal,
  'documents' : IDL.Vec(Document),
  'dateOfBirth' : IDL.Text,
  'fullName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'licenseType' : LicenseType,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'declarationAccepted' : IDL.Bool,
  'remarks' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Fee = IDL.Record({
  'licenseType' : LicenseType,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Statistics = IDL.Record({
  'total' : IDL.Nat,
  'pending' : IDL.Nat,
  'approved' : IDL.Nat,
  'rejected' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(LicenseApplication)], ['query']),
  'getApplicationStatus' : IDL.Func([IDL.Nat], [Status], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func([IDL.Nat, IDL.Text], [ExternalBlob], ['query']),
  'getFees' : IDL.Func([], [IDL.Vec(Fee)], ['query']),
  'getFullApplication' : IDL.Func([IDL.Nat], [LicenseApplication], ['query']),
  'getStatistics' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(LicenseType, Statistics))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setupAdminWithPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'submitApplication' : IDL.Func([LicenseApplication], [IDL.Nat], []),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Nat, Status, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({
    'documentType' : IDL.Text,
    'blobId' : ExternalBlob,
  });
  const LicenseType = IDL.Variant({
    'supervisor' : IDL.Null,
    'wireman' : IDL.Null,
    'workman' : IDL.Null,
  });
  const LicenseApplication = IDL.Record({
    'id' : IDL.Nat,
    'nicNumber' : IDL.Text,
    'status' : Status,
    'applicant' : IDL.Principal,
    'documents' : IDL.Vec(Document),
    'dateOfBirth' : IDL.Text,
    'fullName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'licenseType' : LicenseType,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'declarationAccepted' : IDL.Bool,
    'remarks' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Fee = IDL.Record({
    'licenseType' : LicenseType,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Statistics = IDL.Record({
    'total' : IDL.Nat,
    'pending' : IDL.Nat,
    'approved' : IDL.Nat,
    'rejected' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllApplications' : IDL.Func(
        [],
        [IDL.Vec(LicenseApplication)],
        ['query'],
      ),
    'getApplicationStatus' : IDL.Func([IDL.Nat], [Status], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func([IDL.Nat, IDL.Text], [ExternalBlob], ['query']),
    'getFees' : IDL.Func([], [IDL.Vec(Fee)], ['query']),
    'getFullApplication' : IDL.Func([IDL.Nat], [LicenseApplication], ['query']),
    'getStatistics' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(LicenseType, Statistics))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setupAdminWithPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'submitApplication' : IDL.Func([LicenseApplication], [IDL.Nat], []),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Nat, Status, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };