/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Document { 'documentType' : string, 'blobId' : ExternalBlob }
export type ExternalBlob = Uint8Array;
export interface Fee {
  'licenseType' : LicenseType,
  'currency' : string,
  'amount' : bigint,
}
export interface LicenseApplication {
  'id' : bigint,
  'nicNumber' : string,
  'status' : Status,
  'applicant' : Principal,
  'documents' : Array<Document>,
  'dateOfBirth' : string,
  'fullName' : string,
  'submittedAt' : bigint,
  'email' : string,
  'licenseType' : LicenseType,
  'address' : string,
  'phone' : string,
  'declarationAccepted' : boolean,
  'remarks' : [] | [string],
}
export type LicenseType = { 'supervisor' : null } |
  { 'wireman' : null } |
  { 'workman' : null };
export interface Statistics {
  'total' : bigint,
  'pending' : bigint,
  'approved' : bigint,
  'rejected' : bigint,
}
export type Status = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllApplications' : ActorMethod<[], Array<LicenseApplication>>,
  'getApplicationStatus' : ActorMethod<[bigint], Status>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[bigint, string], ExternalBlob>,
  'getFees' : ActorMethod<[], Array<Fee>>,
  'getFullApplication' : ActorMethod<[bigint], LicenseApplication>,
  'getStatistics' : ActorMethod<[], Array<[LicenseType, Statistics]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setupAdminWithPassword' : ActorMethod<[string], boolean>,
  'submitApplication' : ActorMethod<[LicenseApplication], bigint>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, Status, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
